name: rust-rest-api

services:
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgres://user:password@db:5432/mydatabase"
    ports:
      - "3000:3000"
    networks:
      - default_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
    ports:
      - "5111:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-mydatabase}'"
        ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default_network

volumes:
  db_data:


networks:
  default_network:
