name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest 
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: user
          POSTGRES_DB: test-db
          POSTGRES_PASSWORD: password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql://user:password@localhost/test-db
      RUST_LOG: debug
      HOST: 0.0.0.0
      PORT: 3000
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup Database
      run: |
        cargo install sqlx-cli --features postgres
        sqlx db setup
    - name: Build
      run: cargo build --verbose
    - name: Run unit tests
      run: cargo test --verbose